### ISSUE TITLE
Merge and hide gesture typing

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#1076]
Should be available only in debug builds.
Anything that ships to Play-Store should not include it.

**Comment by LuccoJ** [comment]
Is this because it's still in an overly experimental state, or is there some particular reason why it shouldn't be *in the Play Store* specifically? I've been rather eager to get this feature (I usually source my software from F-Droid, though, not from the Play Store, but that doesn't ship debug builds either).
