### ISSUE TITLE
Clearer dictionary picking menu

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#1094]
Refining https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/832

1. Use checkboxes
2. Clearer language
3. Do not close menu after picking

**Comment by maverick74** [comment]
Manny, the new settings layout is great!!! Congratulations!!!
However, as part of this bug and #832 i believe something like this would make it much more intuitive for the user to know what his doing:

![layout_language](https://user-images.githubusercontent.com/14912461/30698902-2cca3458-9edb-11e7-9d57-ae7979c72031.png)
 

this way there is a clear separation where to choose a keyboard layout and where to choose which languages/dictionaries we want to have available in that keyboard layout ;)

This is just an idea, of course :)

**Comment by maverick74** [comment]
@menny What's your opinion about my suggestion? =)

**Comment by maverick74** [comment]
@menny 
sorry for keep posting on a closed bug. 

Do you think this is viable? 
Should I open a new bug report or you don't like the idea?

**Comment by menny** [comment]
I'm not sure what is the benefit of this separation. Can you provide more details?

**Comment by maverick74** [comment]
Sure i can @menny (sorry for taking this long to reply.......)

**Present situation:**
when one goes to the to the option of "**Enable keyboards and languages**", we are presented with a few keyboard layouts, but:

**a)** there is no _clear_ indication that enabling _Layout X_ also enables _Language X_.
**b)** you have QWERTY Layout for English, QWERTY Layout for Spanish, QWERTY Layout for Portuguese, QWERTY Layout for [insert language here]... It may cause confusion
**c)** (and more importantly) It brings user into the confusion that they **have** to use _Layout X_ to have _Language X_

**With the change proposed:**
**a)** it would became clear that we can use _any_ keyboard layout with _any_ language!
**b)** it would be clear where to go to choose how we want the keyboard to look like and where to go to enable the languages we want to work with

**Case:** 
I want to use the **"16 Keys" keyboard layout**, _but i don't need or want English language enabled_. 
I, instead, want to use **Portuguese language**, _but i don't want to use the Portuguese layout_ (which is actually, just a duplication of English QWERTY layout - to be honest it does not make much sense to have two QWERTY layouts!)

Please, if you find it too confusing or think it does not worth considering i may try to explain it better with a few more time... my english is far from perfect =)

**Comment by maverick74** [comment]
@menny what you think of it?

**Comment by menny** [comment]
Maybe it is something we can do in the future, but right now it's way to complex to implement given the current state of logic around layouts

**Comment by maverick74** [comment]
Well, honestly, from "where i stand" i though there were two path possible: 
Either i was completely wrong and this would be an easy thing to do OR this would be an hard fish to get. 

I was a bit more inclined to the last one because of the fact that Layouts came bundle in a single package with Languages (but maybe there could still be a workaround...).

Still, even this not being "super important", i believe you really should consider it in the future. Still, despite my effort to simplify things, my logic can also be totally wrong and i can be proven wrong (It happen before ;)

Anyway, thank you, @menny , for your work and your consideration for the community!!! ASK really does makes a difference!!!

**Comment by fteppe** [comment]
I would just like to say that I would love that as well, I speak both french and english on a daily basis and I haven't seen a english dictionary with an AZERTY layout. 

If I want to speak english I need to go in QWERTY then back to AZERTY when I speak in french again. SInce I use a lot of english words even in french the switch can be a pain.

**Comment by maverick74** [comment]
@fteppe you can already do what you want with the present version!!! (using azerty layout with both english and french dictionary)
The only problem is that it's not very easy/intuitive to get there - and that's the reason for this suggestion.

I would tell you the steps myself, but my phone broke :(

maybe @menny can provide you the steps/guide to set it.

also, @menny , wouldn't it be better to keep this feature open for easier tracking it in long term?

**Comment by bipox** [comment]
Hi maverick, could you explain how to do it?

People want to type in English with the layout they're used to in their own language. I install this keyboard once a year to see if this has changed, because without this feature its impossible to use.

Imagine every time you go to github your keyboard would suddenly change from QWERTY to dvorak for some reason. yeah...

**Comment by maverick74** [comment]
Hi @bipox 
It's actually easy to get there, it's just not very intuitive!

1. Select all the keyboards you need (unfortunately even if you don't want to use (e.g.:) the french keyboard layout, if want to use the french dictionary you **do need to select** the french keyboard layout).
2. After you select the keyboard layouts you need, just try typing something somewhere, and then **press and hold the "enter" key** 
3. You'll see a popup menu showing up 
4. In this menu you must select the option "Override active dictionary"
5. Then you select the dictionaries you want to be available as you type.

Issue #1341 presents a possible solution.

Still, i would like to bring @menny attention on the issue, since this is becoming a recurrent problem

**Comment by bipox** [comment]
@maverick74 so it seems I can use the keyboard in french and English at the same time without switching keyboard language and with an azerty layout.

As Swiftkey does.

And yet this function is hidden and not advertised anywhere (or I missed it)

Anyway thanks for the help, I can now give AnySoftKeyboard a shot

**Comment by maverick74** [comment]
@bipox 
Yes, you can do it and ASK is just as good as the others or even better. 

And no, you did not missed it! And that's exactly my point! :)

A menu entry somewhere (such as in the screenshot above or as described in #1341 by merlignux) would do the trick!

**Comment by AnXh3L0** [comment]
I understand that the menus and options are a bit not clear at the moment; just letting you know I'm working on some mockups to fix these problems and will work with @menny and others if they want to contribute to apply them to ASK.

**Comment by maverick74** [comment]
@AnXh3L0 that is great news!!! :D

Concerning the GUI, to me, this is the only thing i see that really needs to be addressed. I've already replied several times to various users about how to enable different dictionaries to use with different keyboards.

Replying does not bother me, but i also feel it should be addressed!

The need to download the language packs (that include Keyboard layouts and languages) from Google Play / F-Droid is ok as it is but the GUI should indeed allow users to easily understand they can choose to use Keyboard Layout X with Dictionary Y.

Is there a place where one can follow your progress and see the mockups?

**Comment by AnXh3L0** [comment]
Thanks for replying to others @maverick74, it really helps as we don't really have the time to follow up with everything that happens here in GitHub.

As you might know I'm a new "insider" in the project as I designed the new ASK website a while back, so now I'm working on a complete redesign of the UI. My aim would be to give ASK a modern UI and better UX but that could limit us in the availability of the app as we might need to bump the minimal supported Android version, so we'll see about that.

At the moment, the mockups are something I'm working on locally and will share via an open system that allows people to comment directly on them, give feedback and leave comments. I usually lurk in the Gitter chat so you can keep up there but I'll also share it around here when I'm done.

Thanks once again and cheers.

**Comment by maverick74** [comment]
I try to help as much as i can, but my time is not much either.

If you can / remember notify me when you get something around here (github). 
Will love to see the new look of ask :)

If i can help in anyway, say so :)

(great work with the ask webpage, by the way)

**Comment by AnXh3L0** [comment]
Sure, I'll let you know when I'll come up with something :grinning:

**Comment by mmatous** [comment]
A bit of a necropost but this needs to be reopened and @maverick74's mockup implemented. I came here to request multiple-languages-per-layout feature only to find out that ASK can do it since forever. I don't think it's discoverable without digging through github issues though.

**Comment by maverick74** [comment]
@mmatous ... meh... i've been crying around for some "things" (such as this request and T9, for example) on ASK for a few _**years**_ now, only to see very few things implemented...

I don't believe there will be any changes neither here nor in t9 support. It seems there are not many users/developers interested on them, so everything else gets done first...

as such, from my experience, and if you don't want to get as frustrated about ask as i am, don't hold your breath on this.

**Comment by maverick74** [comment]
@AnXh3L0 so... Out of curiosity... There's still nothing new about your idea?

**Comment by Krzmbrzl** [comment]
Let me jump on this PR as well: I agree with maverick74 that the current UI for having multiple dictionaries available from a single layout is pretty cryptic.

Dictionaries and keyboard layouts are two very distinctive things and as such they should have their own settings entry. This would also prevent me from having to use the override dictionary action if I want to use multiple dictionaries at once (because I frequently switch between languages).
I had to come here to find an explanation on how this can be done which is unfortunate.

So _please_ consider implementing the mockup
