### ISSUE TITLE
Add option to change layout-switch shortcut

### ISSUE THREAD

**Issue by AlexCzar** [AnySoftKeyboard/AnySoftKeyboard#111]
Many people use bluetooth keyboards with their android devices (as do I). Some of us need more than one layout and ASK is the best keyboard for this (in my opinion at least). Current shortcut (shift+space) to change layout is counterintuitive for any person used to hardware keyboards. Can you please add the option to select another shortcut (preferably customizable) e.g. on my PC I use Shift+CapsLock (which also isn't a standard, I know), but at least addition of Ctrl+Shift and Alt+Shift options is a must.

**Comment by ildar** [comment]
I'd also suggest a combination without Shift: the KeyRelease for Shift may come too late and pressing SPACE produces unintended layout switch.
Example: Typing the text "Choose the best OS now!" makes the layout switch before "now" word, because the "S" (with Shift+s) followed by the SPACE so ASK switched the layout :(((
Please fix. Or should I file another bug for this?
