### ISSUE TITLE
Short-tapping emoji key should open emoji menu

### ISSUE THREAD

**Issue by contrapunctus-1** [AnySoftKeyboard/AnySoftKeyboard#1242]
Hey folks. Thanks for your work on AnySoftKeyboard! 😃

I'm using v1.8.1333 from F-Droid, and have noticed that since quite a while, ASK has had an emoji key which, on short-press, inserts '😃', and on long-press shows the emoji selection menu. I find this an odd choice, as I'm invariably reaching for the menu far, far more often than using that one particular emoji.

I'd like to suggest the following possible behaviours -
- short-press opens the emoji menu, long-press is user-customizable, letting the user jump to a certain section of emojis directly, OR
- short-press jumps to the history section of the menu, long-press jumps to the last-open section in the menu (as it does now).

**Comment by menny** [comment]
We have something similar to that right now: Look it up in the "Quick text keys" section in the settings app.

About the fdroid release, we have an issue with releasing there right now. I hope it will be fixed with the next release.

**Comment by contrapunctus-1** [comment]
@menny thanks for your response - I've often noticed the quick text keys settings, but I'm afraid I just don't understand how that works, nor was I able to find any documentation about it...

**Comment by hugomg** [comment]
First, go to the anysoft settings (system / language & input / virtual keyboard / anysoft). Then, go to the emoji order tab. At the top there should be a triple dot hamburger menu with a singlu option (tweaks). This opens a new window with more advanced emoji keyboard settings, including one for swapping the short and long press behaviors for the emoji button.

(Btw, my menus are in portuguese so the actual english names for what I said might be a bit different)

I am currently using the fdroid version so presumably the issue menny mentioned is already fixed.

I do have to say this could be a bit more discoverable... I only found out this feature existed because I came across this issue, after having encountered the exact samd problem...

**Comment by contrapunctus-1** [comment]
Thanks a lot for pointing that out, hugomg! 😀

I agree that it could be more discoverable...but I also hope that one of these behaviours can be the default, as the current default behavior doesn't seem very useful.

**Comment by jwsp1** [comment]
Imo this should be standard behavior. Short tap to show emoji list should be enabled by default.

**Comment by gabrc52** [comment]
I agree that it should be the default behavior. I highly doubt most people want to type exactly 😃 when pressing on that key.

**Comment by NicoHood** [comment]
Same
