### ISSUE TITLE
Key repeat not working in 1.9.1117

### ISSUE THREAD

**Issue by gazixx** [AnySoftKeyboard/AnySoftKeyboard#1243]
### Steps to reproduce
1. Ensure key repeat is enabled
2. While typing text hold key pressed

### Expected behaviour
After a short time key should be repeated until it is released

### Actual behaviour
Key is not repeated

**Android OS version:**
6.0.1

**Device manufacturer and model:**
Samsung Galaxy S5

**List of installed add-ons (like languages, or themes):**
German language pack.
Simple black theme.

**Comment by menny** [comment]
By default, all keys are non-repeatable. Some are (backspace, arrows).
The problem with having keys repeatable by default is that it might confuse users: when you press `A` for a long time, a popup shows up with accent options. As a result, you can not have `A` repeatable.
On the other hand, on long-pressing `V`, there aren't any accents and popup is not shown. Having the key (in this example `V`) repeat and another key (in this example `A`) do not repeat is confusing, and because of that we decided _not_ to have repeatable keys as defaults. Does this make sense?

**Comment by ceciliawolf** [comment]
1. I  want just the space bar to repeat. It's usefull for tables in txt file. Example:
<date> <description> <value>
99/99/99  xxxxx       99,99
99/99/99  zzz             9,99

2. what's the use for said option? What about an option to repeat just the space?
