### ISSUE TITLE
Letters are not seen when using the screen horizontally (Samsung S5)

### ISSUE THREAD

**Issue by loomerco** [AnySoftKeyboard/AnySoftKeyboard#1261]
### Steps to reproduce
1. verify the screen rotation function on your phone is active
2. activate the keyboard in the usual way, using an app that can rotate (like WhatsUp).
3.Activate the keyboard in the usual way (by pressing the typing line).
4. rotate the screen horizontally. make sure the display rotates.
5. in this state, when typing, the cursor does move but the typed letters are un-seen. this was not like this in the past.

### Expected behaviour
The letters should be seen while typing regardless of screen's or app's orientation.
### Actual behaviour
letters are not seen while typing with the screen in horizontal mode. the cursor is seen and moves.
**Android OS version:**
6.0.1
**Device manufacturer and model:**
Samsung S5 LTE model: SM-G900F
**List of installed add-ons (like languages, or themes):**
Hebrew for AnySoftKeyboard

**Comment by alajovic** [comment]
I am affected by this issue, too. The text seems to be white on white background. I do have a few clues that might help the developers determine the source of the problem:

The problem is present in virtually all input fields in all applications, with one exception. I use the K-9 mail application for e-mails, and when composing a message, the text is displayed normally when I'm in the "Subject" input field, but not when I am writing the body of the message. In fact, if I tap into the subject field, and then back into the message body, I can temporarily see the text. If I recall correctly, the text is visible until I create a new paragraph, and then it becomes invisible again. Also, if I close the keyboard when the message body is visible, then reopen it by tapping into the message body, the keyboard reappears, but the text is again invisible.

I noticed that the problem disappears completely if I select the white theme for the keyboard (but I very much dislike the high contrast of that theme, so I would love to have the black one working).

**Android OS version:**
6.0.1
**Device manufacturer and model:**
Samsung A5 SM-A500FU
**List of installed add-ons (like languages, or themes):**
Layouts: Slovene, Lithuanian, SSH

**Comment by alajovic** [comment]
Forgotten piece of info: I'm using AnySoftKeyboard version 1.8-r12 installed from F-Droid.

**Comment by alajovic** [comment]
I just installed version 1.9-r1 from F-Droid, and the issue is still present. However, I just found out that I can avoid it by turning off the full-screen mode in horizontal position. That is, if the setting

Settings -> UI -> Tweaks and more -> Tweaks -> Use full-screen editor in landscape

is turned on, then I get white text on white background when in landscape mode. If I turn it off, then the text is normally visible. Indeed, this seems to be connected with the fullscreen mode, because if I turn on the setting "Use full-screen editor in portrait", the text is invisible also in portrait mode.
