### ISSUE TITLE
Keyboard Does Not Close After App Closes, Keyboard Stays Open On Home screen

### ISSUE THREAD

**Issue by shagele** [AnySoftKeyboard/AnySoftKeyboard#1278]
### Steps to reproduce
1.Open any app that uses the keyboard.
2.Type some information into the app.
3.Leave keyboard open in the app but close the app.

### Expected behaviour
Keyboard should close and leave a normal looking home screen.

### Actual behaviour
Keyboard remains open on the home screen.

**Nougat 7.0

**Device manufacturer and model:**Samsung Galaxy S8

**List of installed add-ons (like languages, or themes):**English language, Nova launcher

**Comment by menny** [comment]
I noticed it is easy to reproduce if I open the Emoji or utility keyboard before hitting the HOME key.

**Comment by ViXXoR** [comment]
So I've been looking into this, and from what I can tell there's no way from the keyboard to know how the user is exiting the keyboard view. I tried different things like using an EditorInfo to try and see if there is a valid input, or trying to hook into onFinishInput() or various other functions.

I have some working code that can solve the issue, but what it does is if the user pushes back from the Emoji keyboard, the keyboard is hidden. If the user wants to go back to the default keyboard, they need to hit the key on the emoji keyboard that takes them back.

I played another with other keyboards, and it seems they all have this behaviour, and I assume it's due to the issues we are seeing here.

I'll open a PR to show the small fix, in case there is interest.
