### ISSUE TITLE
"I" is not capitalised in English

### ISSUE THREAD

**Issue by ItStillDoesNotWork** [AnySoftKeyboard/AnySoftKeyboard#1312]
### Steps to reproduce
1. Type the letter 'i' in a sentence

### Expected behaviour
It should be capitalised, because that is basic English grammer

### Actual behaviour
It isn't.

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by LugiaDepression** [comment]
We requested better suggestions, pointed out several major errors in suggestions months ago, such as last year too from time to time, and it's every time just gets worse. Seems like it's not even worth to share in the issue section because it's only making your fingers tired for nothing. :/ The new emojis was friggin important, but not the keyboard would automatically suggest basic words in their correct way, like "I" or "won't" or "don't" and others.. uh, where is priority nowdays
