### ISSUE TITLE
can't find underscore

### ISSUE THREAD

**Issue by Rxywyn** [AnySoftKeyboard/AnySoftKeyboard#1362]
usually i would be able to tap on the 123 key twice to get to more symbols, but it seems like right now it wouldn't work and i cant access ubderscores. i am currently using the newest beta version 1.9-r3. im running android 7.0. im not sure if this is a bug or a fault on my end, would be great if someone could advice me. thanks!

**Comment by ArenaL5** [comment]
Right now it's on the second page of the symbols keyboard. Tap the 123!#() key, then the {}_ key above it, and you should see it just above the spacebar.

Typing it from the main keyboard depends on what bottom row you're using, and also whether the text field in focus is URL-typed, password-typed, email-typed, or for regular text.

Tapping 123 twice actually returns to the alphabetic key.

Given that this bug is a year and a half old, I suspect it was just fixed in a random PR.

**Comment by AnXh3L0** [comment]
This bug seems to have been fixed. Closing the issue.
