### ISSUE TITLE
double space after word selection

### ISSUE THREAD

**Issue by dbolton** [AnySoftKeyboard/AnySoftKeyboard#1433]
### Steps to reproduce
1. Star typing word
2. Select a suggested word from the top row
3. Press spacebar twice to finish sentence

### Expected behaviour
Word, period, space 
(This is how the built in keyboard worked)

### Actual behaviour
Word, space, period, space 
(I understand why this happens, but I cant think of a time when I would actually want it to behave this way.)

**Android OS version:** 7.0

**Device manufacturer and model:** LG

**List of installed add-ons (like languages, or themes):** lean dark theme, English

**Comment by moshpirit** [comment]
It should be like just {word}{space}, right? If so, I absolutely agree, thanks for reporting!

**Comment by dbolton** [comment]
@moshpirit I'm not sure I understand the question, but yes it should be {word}{space}, until you press double space then it should change to {word}{period}{space}. That is the behavior using the default keyboard on my phone so it is also habit for me.

**Comment by ViciousPenguins** [comment]
I'm still seeing the exact behavior that dbolton described . <- Coincidentally, it just dit it again. I didn't even try.  o_O 

I can reliably repeat this by:
1 - Begin typing a word.
2 - Select a suggested word from the list above the keyboard .
3 - Tap space bar twice to insert 'period+space' and end up with 'space+period+space'.

This seems like the kind of bug that should be squashed in less than nine days, rather than more than nine months, especially considering the quality of the app otherwise . This keyboard is is pretty amazing, aside from this one little issue . I may have to turn off 'space after candidate pick' until it's addressed. :-(

**Comment by Strubbl** [comment]
pls dont close .thx

**Comment by menny** [comment]
This is what will happen in the next release (and current beta):

1. Start typing "wor"
1. Select a suggested "word" from the top row
1. Press the spacebar to finish the sentence. (notice, one press on the spacebar).

output: `word. `

Another use-case:

1. Start typing "wor"
1. Press the spacebar to auto-pick the first suggested "word" from the top row
1. Press the spacebar again to finish the sentence.

output: `word. `
