### ISSUE TITLE
Add secondary dictionary to keyboard layout

### ISSUE THREAD

**Issue by tpimh** [AnySoftKeyboard/AnySoftKeyboard#1524]
I'm using English keyboard layout, but sometimes I input Finnish text. It would be great to have Finnish as secondary dictionary, so I can use both languages with correction and prediction without adding extra keyboard layout.

**Comment by maverick74** [comment]
Hi @tpimh 
The feature already exists!

1. Select all the keyboards you need (unfortunately even if you don't want to use (e.g.:) the french keyboard layout, if want to use the french dictionary you **do need to select** the french keyboard layout).
2. After you select the keyboard layouts you need, just try typing something somewhere, and then **press and hold the "enter" key** 
3. You'll see a popup menu showing up 
4. In this menu you must select the option "Override active dictionary"
5. Then you select the dictionaries you want to be available as you type.

I think your problem is more related to issues #1341 and #1094

**Comment by tpimh** [comment]
Thank you! It worked. Kinda. I will now try to get used to it and reopen if it doesn't work as expected.
