### ISSUE TITLE
[Help] how to use clipbaord fine select?

### ISSUE THREAD

**Issue by Tikotik** [AnySoftKeyboard/AnySoftKeyboard#1588]
I think that by first pressing 'fine select' #1527 from utility keyboard and then the left and right arrow keys, you can add individual letters to selection. 

 Is that the intended use? and can I remove single character from selection?
@pelya

**Comment by pelya** [comment]
Yes, it's supposed to be the same as holding Shift key and pressing arrow
keys on PC keyboard.

It's a bug that you cannot remove characters from selection, because it
does not track whether the cursor was on the left or on the right side, so
it can only grow the selection. I just was too lazy to fix it.
