### ISSUE TITLE
[Feature request] Move my spacebar

### ISSUE THREAD

**Issue by botoxi** [AnySoftKeyboard/AnySoftKeyboard#1620]
Hi,

Thanks for your nice work, I like the behavior of your keyboard and wish one more little gimmick :)
I want move my space bar besides the enter button. Mark and comma shall be positioned on the left. 

Because I hit always those keys with my right thumb while aiming the spacebar ;)

If I can change it by my own, I will be thankfull for hint.

**Comment by VitaliPom** [comment]
Hi @botoxi  are you talking about something like this https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1600 or are you willing indeed really move your space bar closer to the enter key in order to type with one hand? Are you aware there is a split option capability? -- just make a "zoom" movement on the keyboard screen to enable this option.

**Comment by botoxi** [comment]
thanks for the hint. I tried the split option. It does not effect the spacebar like i would like to use it.

Yes, i would appreciate it alot to use the spacebar straight besides the enter-key :)

**Comment by botoxi** [comment]
*push*

I hope its okay to push my request after three months. I am still in hassle to hit the spacebar without.hitting.the.mark ^^

**Comment by Soundtoxin** [comment]
Moving the space next to enter sounds like a good idea. That's how my split pc keyboard is.
