### ISSUE TITLE
Pressing backspace on special characters causes an unknown character to appear

### ISSUE THREAD

**Issue by vincentmacri** [AnySoftKeyboard/AnySoftKeyboard#1636]
### Steps to reproduce
1. Type any special character with a Unicode value above U+FFFF. For example, emoji such as 😃, or double-struck math letters (which is how I found this bug) such as 𝔾.
2. Press space
3. Press backspace

### Expected behaviour
Pressing delete after a space should only delete the space.

### Actual behaviour
The space is deleted and the special character is replaced with �.

**Android OS version:**
8.1.0, running Lineage OS

**Device manufacturer and model:**
Google Nexus 6P

**List of installed add-ons (like languages, or themes):**
Only a custom language pack that I'm working on https://github.com/TheVirtualMachine/LanguagePack

This is a language pack for math symbols. I discovered this bug while testing the double-struck characters. This bug occurs for all double-struck characters except ℚ, ℝ, ℙ, ℍ, ℤ, ℂ, ℕ, which are precisely the double-struck characters with Unicode values BELOW U+FFFF.

**Comment by ZorvyY** [comment]
I reproduced the bug on a fresh install with no add-ons. I used a Galaxy Note 8 running Android version 8.0.0.

**Comment by menny** [comment]
thanks for reporting.

**Comment by TheVirtualMachine** [comment]
A possibly related issue to this is that if one of those special characters is set as a `popupCharacter` AnySoftKeyboard interprets it as two separate popup characters, both of which are rendered as �. After entering both �s into the textbox, the desired character is displayed.

I feel that this and the issue I reported are likely caused by the same bug.

**Comment by poet-man** [comment]
I can repro this on my Galaxy S4
