### ISSUE TITLE
[Feature Request] Android Direct Boot Support

### ISSUE THREAD

**Issue by MilesBreslin** [AnySoftKeyboard/AnySoftKeyboard#1710]
Allow for a basic, direct boot aware keyboard to popup upon password entry after reboot.

**Comment by billie80** [comment]
I also support this feature. If I am correct this would allow to replace the stock keyboard completely which at the moment is still required for the initial login after a reboot.

**Comment by menny** [comment]
I have a proposed fix (I'm not sure it will fix the problem, since it seems that different devices behave, well, differently).
Is anyone willing to test it out? Please do so only if you have a way to type in the passcode in case this fix is not valid.

**Comment by billie80** [comment]
That's great news. Happy to test. It shouldn't be a problem if other keyboards with direct boot support are available. Else I am able to log in using an USB keyboard.
Btw, florisboard also implemented it recently and it works as expected here.
Maybe it works as an inspiration:
https://github.com/florisboard/florisboard/search?q=Direct%27+boot&type=commits

**Comment by menny** [comment]
Okay, I went with a similar approach.

**Comment by menny** [comment]
[ime-app-7386.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/8484476/ime-app-7386.zip)

**Comment by billie80** [comment]
Uninstalled first as I use the F-Droid build. It did not work unfortunately. Disabled all keyboards but ASK. Had to log in using the USB keyboard!

**Comment by menny** [comment]
[ime-app-7388.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/8486059/ime-app-7388.zip) <- another try

**Comment by billie80** [comment]
Unfortunately it still doesn't work here. Any information I can provide to help debugging things?

**Comment by menny** [comment]
Can you generate a debug report? On my phone I can do that in the Developer Options.

Reboot your device, while using the latest APK I sent, and having AnySoftKeyboard the only enabled keyboard, and generate the report immediately after unlock. The report is a zip file with lots of logs and crash reports. 

Email the report to me, rather than attach it here

**Comment by menny** [comment]
Also, can you provide your exact setup?
Which device you have? OS version? How do you set up your locks? And what is the actual behavior when rebooting?

**Comment by billie80** [comment]
The device I use is not really mainstream. It is a [Shift6mq](https://shop.shiftphones.com/shift6mq.html)! It currently runs Android 10 without a lot of modifications, so it should not deviate from AOSP much! I use fingerprint for unlocking but for the initial startup it requires a password. When I reboot I get prompted with the request to input the password which is not possible because the keyboard does not pop up when I select the input field.

As requested I will send you the debug report by mail.

**Comment by menny** [comment]
thanks

**Comment by menny** [comment]
wait... Android 10? I only tried on Android 9! Let me try that
