### ISSUE TITLE
Words randomly deleted when trying to manually fix typos

### ISSUE THREAD

**Issue by Tahvok** [AnySoftKeyboard/AnySoftKeyboard#1900]
Latest beta deleting words randomly when try to fix typos manually.

I must add I do not use the suggestions, and prefer to type and fix things manually.

Basically, what happens is when you delete some characters, and try to type the new character, it replaces the whole word. I'm not sure when it decides to do this. Only thing I notices is that some times it will highlight with underscore the word it's going to delete - but not always.

It's so unreliable right now, and makes typing hard as I need to constantly look that it did not delete a word..

### Steps to reproduce
Not sure. You can try deleting characters then writing, sometimes it happens.

### Expected behaviour
Should not delete words randomly

### Actual behaviour
Deletes words randomly

**Android OS version:**
7.1.2

**Device manufacturer and model:**
ZTE Axon 7

**List of installed add-ons (like languages, or themes):**
Russian,Hebrew,Using the dark theme

**Comment by KuchiSofts** [comment]
Same here, just start few days ago when trying to delete 1 letter its delete the entire word or few words
I have the app for more than 4 years and its start to do this few days ago

**Steps to reproduce**
typing some text and i tried to delete last letter and sometimes it's delete the entire word sometimes few words
its stop for few min if i turn off the suggestions but its back 

**Expected behaviour**
Should not delete words only the last letter 

**Actual behaviour**
Deletes words instead of letters

**Android OS version:**
8.0.0

**Device manufacturer and model:**
HTC U11

**List of installed add-ons (like languages, or themes):**
English,Hebrew
Using Plain Dark theme

**Comment by spacekatia** [comment]
disabling suggestions seems to work as a workaround.

same issue, android  6.0 on LG G4 with German (Neo 2) keyboard

**Comment by IronJunkie** [comment]
Same for me on Android 10, Essential (stock), it also carries over to next word or there is an invisible field there or something, not 100% sure

**Comment by anakov95** [comment]
I just tried enabling shifted backspace and I haven't got the issue, I'll keep using the keyboard for another day and report back, for now I'd suggest everyone who has this same issue to do the same, it's under Languages - Tweaks, you can keep suggestions on.

**Comment by KuchiSofts** [comment]
> I just tried enabling shifted backspace and I haven't got the issue, I'll keep using the keyboard for another day and report back, for now I'd suggest everyone who has this same issue to do the same, it's under Languages - Tweaks, you can keep suggestions on.

you mean "Back-wrd support" ? not working

**Comment by menny** [comment]
a fix will be released shortly
