### ISSUE TITLE
Word suggestions are always lower case

### ISSUE THREAD

**Issue by gartenriese2** [AnySoftKeyboard/AnySoftKeyboard#1914]
### Steps to reproduce
1. Use German dictionary. 
2. Type a word.
3. Press space.

### Expected behaviour
Suggestions for the next words appear and are spelled correctly.

### Actual behaviour
All suggestions appear in lower case.

**Android OS version:**
Android 10

**Device manufacturer and model:**
OnePlus 7 Pro

**List of installed add-ons (like languages, or themes):**
German dictionary

**Comment by PFischbeck** [comment]
I found the source of this behavior. It happens because the typed words are already saved in lowercase for the next word suggestions:
https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/0c1df540ba84465c1e5be1de9fe3d1373624f6f6/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java#L224
The current word is lowercased before it is passed to the `mSuggestionProvider`, which then passes that lowercase word on to the `NextWordDictionary`.
https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/cad0bdb35fe4eeea260bdff1f4a8cb67e3a05914/app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java#L459

**Comment by AnXh3L0** [comment]
Thank you @PFischbeck for debugging this, maybe @ArenaL5 or @menny can implement the change?

**Comment by ArenaL5** [comment]
Thank you for your help! It's really easy to fix when something tells you what to change.

I'll include this commit in my next pull request, hopefully this week (I'm trying to fix another issue and I've only done part of the work.

How come you didn't send a pull request yourself, @PFischbeck?

**Comment by PFischbeck** [comment]
@ArenaL5 I currently don't have the project set up locally. Additionally, I wasn't sure whether just removing `.toLowerCase(mLocale)` would be okay, as this might have some side effects.

Currently (I think), if I type `This is`, then `this->is` is saved as a possible next word suggestion.
With the change, this changes to `This->is`, meaning that not only is the next word case-sensitive, but the current word too. In languages like German with many Capital letters, this will probably improve things (since the next words of a noun and a verb/adjective should be quite different, even if they are the same in lowercase). However, in most languages, this probably means the next word prediction after the first word of a sentence will be bad, or just non-existent.

In terms of design, it would probably be best to pass the words to the suggestions provider unchanged, and then at some later point one could think about handling this in the next word logic.

**Comment by ArenaL5** [comment]
I'm not familiar with the inner workings of the suggestion engine, but this shouldn't bring any problem. The first word of a sentence can't be easily predicted (if it can, the engine should realize that a capital goes after a period in pretty much any language). And the following words follow normal rules.

Any other problem should fade with use as long as you use `this is` (or any other two words) in the middle of a sentence, too. It's difficult to predict if that'll be the case, so I would argue to keep this commit until we receive another issue report.

I'd be more worried by bizarre mid-word capitalizations, both of [proper names](https://en.wikipedia.org/wiki/IPhone) and [regular words](https://en.wikipedia.org/wiki/Irish_initial_mutations).
