### ISSUE TITLE
Suggest pasting from clipboard

### ISSUE THREAD

**Issue by jwsp1** [AnySoftKeyboard/AnySoftKeyboard#1917]
Steps to reproduce
1. Copy some text
2. Close ASK (as if you were switching apps)
3. Tap a message field where you want to paste your copied text
4. No suggestion available on suggest bar.

Improvement suggestion:
After tapping the message field, ASK should suggest inserting the text if the user has not written anything in the meantime (i.e. has not used ASK).

**Comment by PrSunflower** [comment]
I agree with this. On Windows Phones the keyboard had a small clipboard icon at the left side of the suggestions bar whenever something had been copied. See picture [here](https://cdn.wccftech.com/wp-content/uploads/2015/12/wp_ss_20151222_0003-354x630.png).

A "paste icon" shouldn't take a lot of space and it is very convenient.

**Comment by bqv** [comment]
+1

**Comment by Liamb135** [comment]
I really need clipboard access without needing to use gestures for the "utility keyboard".

**Comment by bqv** [comment]
Honestly I just gave up and got a different keyboard…

**Comment by menny** [comment]
will release this in the BETA channel later tonight

**Comment by georg-d** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1917 is a nice feature, but because of some probably simple to implement details it's still far less useful than it may be. See https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2842 and https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2843

**Comment by PrSunflower** [comment]
I agree 100% with @georg-d , I would prefer an improved "Suggest pasting" feature.

**Comment by digitalheir** [comment]
Why was this issue closed? I get no paste suggestion and can't find an option to turn it on either?

![image](https://user-images.githubusercontent.com/178797/133930372-0879f2dd-4eac-4237-bbb8-9ade882f2d49.png)

It would be nice to have cut/copy/paste like this:

![photo1632060287](https://user-images.githubusercontent.com/178797/133930437-1dc91dfa-cc5d-4265-a284-d2a91d6a432d.jpeg)

**Comment by PrSunflower** [comment]
@digitalheir the issue was closed because the feature was implemented as part of [milestone 1.10-r4](https://github.com/AnySoftKeyboard/AnySoftKeyboard/milestone/92). Make sure ASK on your phone is up to date and try copying something, then the next time you touch a text field ASK will suggest pasting in it with a button on the upper-right corner.

For new suggestions see if other issues (for example #2842) don't already suggest what you want and if not, please open a new issue.

**Comment by digitalheir** [comment]
Aha, sorry. I guess I'm still on r3 (version 1.10.1786 downloaded from F-Droid).

**Comment by georg-d** [comment]
@PrSunflower I'm not finding the paste icon in top right. I'm using v1.11-r1 which has a higher version number than mentioned 1.10 and it is the newest available in Google Play Store. Can you help me out?

**Comment by menny** [comment]
@georg-d , this has been released in BETA a while ago. Can you install the beta? Or maybe the new version from Google Play (we are rolling out v1.12 these days)

**Comment by georg-d** [comment]
After roll out of v1.12 via Google Play Store, I updated and the icon is visible 👍
