### ISSUE TITLE
Swipe should prioritize user dictionary / user wordlist

### ISSUE THREAD

**Issue by ysteina** [AnySoftKeyboard/AnySoftKeyboard#1933]
### Steps to reproduce
1. Add a word to user dictionary
2. Try to make the word appear by swiping – swipe over the letters of the word
3. Swipe returns the closest word from the in-built dictionary, not from the user dictionary

### Expected behaviour
There should be an option for swipe to prioritize a word that a user has added to the user's custom wordlist.

### Actual behaviour
Swipe prioritizes words from in-built dictionary or AOSP.

**Android OS version:**
9 Pie

**Device manufacturer and model:**
Sony Xperia XZ1 Compact
**List of installed add-ons (like languages, or themes):**
Norwegian and English languages

**Comment by maxmopp** [comment]
To me it looks like the user dictionary is not read at all when swiping. An added word will be suggested without a problem while typing but does not even show up in the suggestions while swiping.
It would be wonderful if the user dictionary would be read for swiping, as otherwise I really like it.

#### Android OS version: 
LineageOS 17.1 / 10, microg

#### Device manufacturer and model:
Redmi Note 4

#### List of installed add-ons (like languages, or themes):
German and English languages

**Comment by menny** [comment]
this is correct, user-dictionary is not read. We will fix that in the next release.

**Comment by decadent** [comment]
To me it seems like gesture-typing also ignores frequency of use for each word. Even among built-in dictionary words, there are some that I regularly use and always need to type out. (I'm supposing that suggestions normally do keep track of the frequency and bring more-often-used words to the front.)

Not sure if it's affected by my settings. I went through them several times and haven't found anything that would help, to my judgement.

(Haven't seen issues specifically about this, except possibly #1783 “Gesture-Typing suggestions should be sorted by freq and curve-closeness”, which however was apparently fixed a year ago. Dunno if I should open a separate issue but I could do that if it's preferable.)

**Comment by Apflkuacha** [comment]
The names of the contacts are also not suggested when gesture-typing is used. I also really want to vote this issue up, rather want to have it already in the 1.10-r4 release.
Maybe i do have some time the next weeks to look into the code and try to find it myself, i guess it shouldn't be too hard to find & fix.

**Comment by free5lot** [comment]
Any hope this issue will be prioritized? 
It's a real deal-breaker.
Currently Swipe is not working with user dictionary at all. So, it's not an enhancement but bug that prevents from using user dictionary with manually added words.

**Comment by kocjs** [comment]
I am looking for this too, please.

**Comment by free5lot** [comment]
Any hope this issue will be prioritized?
It's a real deal-breaker.

**Comment by bugnano** [comment]
> To me it seems like gesture-typing also ignores frequency of use for each word. Even among built-in dictionary words, there are some that I regularly use and always need to type out. (I'm supposing that suggestions normally do keep track of the frequency and bring more-often-used words to the front.)
> 
> Not sure if it's affected by my settings. I went through them several times and haven't found anything that would help, to my judgement.
> 
> (Haven't seen issues specifically about this, except possibly #1783 “Gesture-Typing suggestions should be sorted by freq and curve-closeness”, which however was apparently fixed a year ago. Dunno if I should open a separate issue but I could do that if it's preferable.)

I don't know about the pull in #1783, but as everyone has a different writing style, there is no single word frequency list that satisfies every user.
The word frequency list should be based on how frequently the user types a certain word, with or without gesture typing (it is important to update the word frequency count also, or should I say especially, when a word is not typed with gesture typing). This way, after a little bit, ASK will adapt to the personal writing style of that particular user.
Today I find frustrating that when I swipe a word, ASK will always use the same wrong word that I never use, instead of a word that I have already used 1000 times, and it still doesn't understand that I'm probably using the word that I use frequently, instead of the other that i NEVER used.
