### ISSUE TITLE
Difference in keyboard between my different applications, especially on my browsers (firefox, chrome)

### ISSUE THREAD

**Issue by Loremipsum103** [AnySoftKeyboard/AnySoftKeyboard#1944]
### Steps to reproduce
1. Keyboard Qwerty CA - FR
2. Theme Yochees Dark - Option 2

### Expected behaviour
I want to have the same keyboard everywhere (cf keyboard in the application screenshot, not my browser's keyboard)

### Actual behaviour
I have a difference in keyboard between my different applications, especially on my browsers (firefox, chrome)
![browser](https://user-images.githubusercontent.com/59610085/71898920-70eed100-3152-11ea-8471-253bdef92558.png)
![other-application](https://user-images.githubusercontent.com/59610085/71898924-73e9c180-3152-11ea-9d23-62ec2ba9513b.png)

**Android OS version:** Android 10

**Device manufacturer and model:** Pixel 3

**List of installed add-ons (like languages, or themes):**

**Comment by Footbath667** [comment]
I also have this problem. ASK appears to have the same layout everywhere, on all of my apps, except for the URL bar on Firefox mobile and Fennec; everywhere else in the browser the keyboard layout is as it should be. The different layouts I have match Loremipsum103's screenshots. This is a minor quibble, but it's annoying because the double quotes, which I often use for search queries, disappear to the 123!#() keyboard. This is on a Sony Xperia XZ1 Compact with Android 9.

**Comment by menny** [comment]
this is by design. We provide different bottom rows in different cases.
You can disable this behavior in the settings app: UI->Tweaks and more->Enabled specialized input-field modes.
