### ISSUE TITLE
Overlapping without a navigation bar

### ISSUE THREAD

**Issue by patlux** [AnySoftKeyboard/AnySoftKeyboard#1951]
### Steps to reproduce
1. Install the recent version on the play store

### Actual behaviour

![Screenshot_20200107-232123](https://user-images.githubusercontent.com/4481570/71934568-07e47900-31a5-11ea-88dc-693c8c25b9bc.jpg)

**Android OS version:**

Android 10

**Device manufacturer and model:**

OnePlus 7 Pro

**List of installed add-ons (like languages, or themes):**

German

**Comment by rien333** [comment]
Personally, I don't really need these icons (there are definable gestures for most of their use cases). I'm pretty sure the same thing happens when the keyboard draws battery saving and night mode icons. Maybe add an option to hide all these extra icons?

**Comment by hraponssi** [comment]
I'm also experiencing a similar issue with android 10 where the bottom keys on the keyboard don't register when I tap them because the taps are registered as being on the navigation bar even though they are on the keyboard. I checked how gboard deals with this and it seems to raise the keyboard higher above the navigation bar, so I would assume something similar could be done here.

**Comment by menny** [comment]
we've created another issue to track this for the next release.

**Comment by rien333** [comment]
@menny what issue would that be?
