### ISSUE TITLE
Use androidx

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#2344]
min SDK level 14

**Comment by eyedol** [comment]
@menny wondering if this issue is still open for contribution. I'm happy to take it.

**Comment by menny** [comment]
Yes, you can take this. Thank you.
But, I will not merge this into master until the upcoming release.

**Comment by menny** [comment]
If you'll like to get something right now, you can take a look at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2502

But, a solution should be verified on devices (or emulators) running Android API 29, and devices running previous versions

**Comment by eyedol** [comment]
Sure. I'll tackle both.

**Comment by menny** [comment]
thank you. #2502 is a high priority, so if you can take a look at that first, it would be great.

**Comment by eyedol** [comment]
I have started the work as a draft PR #2517. It seems this is more than upgrading the support library to `androidx`. With Robolectric 4, when testing `androidx` packages they [recommend you AndroidJunit4](http://robolectric.org/androidx_test/) instead of the RobolectricTestRunner. I see that we do have a custom test runner. I'll need some direction here as I'm not that familiar with Robolectric.

The app itself runs and compiles however tests are heavily broken because of incompatibility I guess. The current change is huge. Let me know how you want us to approach this? Continue with one huge PR and merge when ready? or figure a way to doing this iteratively, ie, adding workarounds where necessary.

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/6c1147dac1fb2381900c8fbb154ce6da4955e8a3
