### ISSUE TITLE
Donation via standard platforms (e.g. GitHub, Patreon)

### ISSUE THREAD

**Issue by PetrVladimirov** [AnySoftKeyboard/AnySoftKeyboard#2500]
@menny thank you for such a great product!

Have you considered linking a standard donation solution to the project, so people can utilize it for recurring donations? It shouldn't be that difficult. Even GitHub has a native functionality for that nowadays. Existing direct links via paypal may not be very suitable in some cases.

**Comment by menny** [comment]
I can't  use GitHub since they require a business-like bank account for organizations account (https://github.com/AnySoftKeyboard). I will try to open a GitHub Sponsors for my account and see if that works.

**Comment by menny** [comment]
something like this:
https://github.com/sponsors/menny
![image](https://user-images.githubusercontent.com/481272/97117821-a1e9c380-16dc-11eb-8c12-a1e8e4f4fa4c.png)

Anyhow, I can't add these links to the app itself, since Google does not allow 3rd-party pay services.

I'll also add those links to the website: https://github.com/AnySoftKeyboard/AnySoftKeyboard.github.io/issues/13#issuecomment-716162234
