### ISSUE TITLE
[Feature Request/Possible PR] Add clipboard-with-history support

### ISSUE THREAD

**Issue by pgp** [AnySoftKeyboard/AnySoftKeyboard#2648]
I've developed a prototype of multi-item clipboard manager for this keyboard.

A friend of mine last week told me: "I'd like to have something like [Ditto](https://ditto-cp.sourceforge.io/) on my smartphone", I thought it would be pretty quick to bring up something working, and so I started working on it, as a standalone clipboard app.
When it was ready, I realized that Android, starting from version 10, requires the calling process to be an IME or a system app in order to intercept clipboard events (excluding the case of on-focus activity), so I remembered about this keyboard app I tried to use some years ago (I admit the UX has improved a lot since then, especially for swipe mode), I forked it and embedded the clipboard classes into it. The forked repo is [here](https://github.com/pgp/AnySoftKeyboard), release APKs are available as well.

I've not submitted this as a PR, for the following reasons:
- I'm not yet sure whether this functionality can be really useful and/or comfortable to more than a few people;
- ClipboardManager's min API level is 11, while AnysoftKeyBoard current min is 9;
- Showing the clipboard overlay requires a signature permission (i.e. for non-playstore signed APK installs, the user has to explicitly grant this permission from OS Settings). Maybe the overlay window can be avoided at all, and a global button for showing clipboard can be added to the keyboard layout (so that when the keyboard hides, the clipboard hides as well)

If this can be an interesting feature to embed, I'm open to discuss this further.

Regards

**Comment by menny** [comment]
oh.. this is interesting.
Can you share some screenshots?

After the upcoming release (r4) we will bump the min-sdk to 14, this will help a bit.

**Comment by pgp** [comment]
Sure, here they are (a screenshot with the main view, and a gif that illustrates an example usage):

[<img src="https://i.ibb.co/L8fBgfK/Schermata-del-2021-01-24-10-36-12.png" alt="screenshot" width="120" border="0">](https://ibb.co/1LxBXxc)

[<img src="https://i.ibb.co/pbQFt3z/example-usage.gif" alt="gif" width="120" border="0">](https://ibb.co/Qpkw26N)

**Comment by menny** [comment]
Have you compared your feature to AnySoftKeyboard built-in clipboard manager? Swipe up from the space-bar and long-press the clipboard-paste icon

**Comment by pgp** [comment]
Well, I didn't know the keyboard supported history out-of-the-box :smile: . A few comments though (imho):

- the swipe-up menu gesture seems a bit uncomfortable, one needs to swipe up across the entire keyboard heigth (also, keys are highlighted during the movement, so one may initially think the gesture doesn't work), while it could suffice to swipe on the space button itself; the only gesture ambiguity would be when swipe mode is enabled, but afaik swipe mode involves single words,
so there would be no problems there as well, if swipe-up length is reduced;

- long click on paste icon is a bit uncomfortable as well, it would better to have an up-arrow icon upon it, bound to a persistent state, in order to show/hide history (the history window should be attached to the option panel, not separated)

- once history is open, window should not close on delete button click (one may want to delete more than one item)

**Comment by Jonta** [comment]
Pinning clips would be nice. I have a few I periodically use over and over again

Nowadays, I have no idea what I'm going to find in this clipboard

**Comment by menny** [comment]
We can open feature requests for:
 * pinning
 * better location for clipboard icon
 * keeping window open when deleting (or pinning) items.

**Comment by menny** [comment]
@pgp or @Jonta feel free to open those with your wishes.

**Comment by Beeblebrox666** [comment]
I like these ideas. Since currently clipboard history defaults to samsung's auto deletion after 60 minutes. I have several things I paste all the time (or want to...) The only thing that worked persistantly was changing the emoji text. That producer this: ∴ It's the therefore math symbol. I also use ∵ which is because symbol. They don't work in the personal dictionary in either Samsung or Anysoft settings. Because I use the Dvorak keyboard I always seem to miss the 'a' key and type 'o'. Example I want to type have, but I accidently type hove. The dictionary switcher does not work to auto correct that. What I would like to see is a separate complete editable panel. Where all you have to do is long press a box and have it come up with a text box to type in what you want the key to display, making it permanent until you change it. I would suggest something formatted similar to the number pad with 16 or 20 boxes. The key would show either the full text if it fits (like 1-4 letters) Or show the first few letters if it in a longer string. On thing I seem to need all the time is: 'stop' I get a never ending barrage of text spam to reply to... Even 12 boxes would be useful. More display room for what it holds. BTW, Samsung doesn't work for an up swipe bringing up the menue that ASK brings up with the clipboard button. (Note: there is a display problem with the popup. It's medium purple with black text and very hard to read. Sometimes. If you do it again then its usually white with black text.) Note: Using the dark system mode.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/1fda6da4-c135-4c1c-97f2-7fcbc453cf53" />
