### ISSUE TITLE
takes a lot of screen space

### ISSUE THREAD

**Issue by funnym0nk3y** [AnySoftKeyboard/AnySoftKeyboard#2886]
Using the keyboard takes a lot of vertical space on my device. It is roughly 25% bigger than gboard on  my device with rounded corners. 

**Android OS version:** 10

**Device manufacturer and model:** Xiaomi Mi8

**List of installed add-ons (like languages, or themes):** German language addon

**Comment by Bradford1040** [comment]
I personally use anysoftkeyboard because of its size! But it would be nice to have it adjustable like say Swiftkey is.

**Comment by funnym0nk3y** [comment]
In my case there is some unnecessary space below the space-bar and above the top row.

**Comment by Bradford1040** [comment]
Are you rooted or use adb? If so, you can create a script or use tasker app and use

`run shell` as root

`wm overscan 0,0,0,-80` or tweak to preference

**Comment by PrSunflower** [comment]
@funnym0nk3y can you post a screenshot here?

**Comment by funnym0nk3y** [comment]
![Unbenannt](https://user-images.githubusercontent.com/41870754/126977454-442378ad-ccd3-4e15-9fcc-b9b72036c3fb.png)

Here you can see the space apve and below the "keys".

**Comment by matheuswillder** [comment]
You can tweak this in the theme settings. The default value is 1.0, put something below that (e.g. 0.5). There are also other possible customization but I haven't tested them all.

**Comment by PrSunflower** [comment]
Hi @funnym0nk3y you should try the previous suggestion (never tried it myself) and tell us how it goes 🙂

<br>

> In my case there is some unnecessary space below the space-bar and above the top row.

Concerning this message:

## I think the space at the bottom is OS-dependent (can someone confirm?)

### On my Nokia running Stock Android

![Screenshot_20210726-205828](https://user-images.githubusercontent.com/59576952/128599964-d82b6232-03d1-403d-98ad-756e123ed577.png)

<br>

### On my Samsung with OneUI

![Screenshot_20210726-203813_QKSMS](https://user-images.githubusercontent.com/59576952/128599971-a6a0f42d-40a6-4a3a-ad2f-8520f9c47809.png)



<br>

<br>

### However my Samsung lets me remove that space

![Screenshot_20210726-203745_Settings](https://user-images.githubusercontent.com/59576952/128599995-f25df2b0-b250-496b-8429-e861b52bd5e5.png)

<br>

![Screenshot_20210726-203656_QKSMS](https://user-images.githubusercontent.com/59576952/128600003-7bac836e-565a-45e0-829c-d5fefbc03730.png)



<br>

<br>

<br>


## Above the top row: 

Looking at your screenshot it seems to me that it's because of the app you're using. I don't have that on most apps:

![Screenshot_20210726-203636_QKSMS](https://user-images.githubusercontent.com/59576952/128600051-54044cbb-4e3c-4489-94e4-5a3057f04ed9.png)

**Comment by matheuswillder** [comment]
Hi @PrSunflower, about the top row: the app in the @funnym0nk3y screenshot appears to be Firefox, and the empty space is just the ASK suggestion bar (it's empty because nothing was typed), I believe the only way to remove this is disable the suggestion bar. As for the space at the bottom, I also think it's OS-dependent (and I keep it hidden on my Samsung).

In other words, aside from the suggestion bar, there is nothing the ASK can do about it.

**Comment by Jonta** [comment]
Seems like the issue has been resolved with the information that one _can_ change the size. =)
