### ISSUE TITLE
Haptic feedback disregards system setting

### ISSUE THREAD

**Issue by Ghostbird** [AnySoftKeyboard/AnySoftKeyboard#3096]
### Steps to reproduce
1. Android 10
2. Haptic feedback disabled in Android
3. Latest AnySoftKeyboard v1.11-r1

### Expected behaviour
No haptic feedback

### Actual behaviour
Haptic feedback is on regardless of system setting

**Android OS version:**
10
**Device manufacturer and model:**
Motorola One Action
**List of installed add-ons (like languages, or themes):**
Dvorak keyboard

As far as I remember ASK has always followed the OS setting for haptic feedback. Since the latest v1.11-r1 it no longer does. It drove me crazy, as it turned on randomly while I was using the phone. I guess ASK had been updated in the background. I thought something was wrong with my Android. Once I realised that the Google keyboard still followed the system setting, I managed to narrow it down to ASK and found the override setting to disable haptics entirely in ASK.

**Comment by SergeantSphincter** [comment]
I'm having the same issue.   I cannot figure out how to turn it off, I've searched everywhere in the app.

**Comment by Ghostbird** [comment]
1. In the ASK app, click the middle icon in the bottom bar (the palette icon). You'll end up in the UI menu.
2. Click the option _Keyboard effects and experience_
3. Disable the checkbox _Use system vibration_ (this one is misbehaving)
4. Set the _Vibrate on key-press_ time to _0 milliseconds_

**Comment by SergeantSphincter** [comment]
I feel like a huge ass, how did I miss that?   I'm so sorry!   Thank you for your help.  I've had ASK for 10 plus years, I recommend it to everyone.   Yall have an amazing product.  
Thanks again!     Mary

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 4, 2021 at 9:36 AM, Gijsbert ter ***@***.***> wrote:   

   
   - In the ASK app, click the middle icon in the bottom bar (the palette icon). You'll end up in the UI menu.
   - Click the option Keyboard effects and experience
   - Disable the checkbox Use system vibration (this one is misbehaving)
   - Set the Vibrate on key-press time to 0 milliseconds

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Setuneh** [comment]
Thank you!

**Comment by menny** [comment]
Is this still an issue @Ghostbird ?

**Comment by Ghostbird** [comment]
It's been an issue since the November 19th release, which I apparently did not get until December the 3rd. I'm currently joining the beta program to check whether it's been fixed there. It takes a few minutes apparently.

**Comment by menny** [comment]
On my devices I haven't seen a haptic on/off switch but do have "intensity" slider. Its value does affect AnySoftKeyboard vibration.
Do you have a different set of system settings?
![Screenshot_20220102-093137_Settings.png](https://user-images.githubusercontent.com/481272/147879043-1bb68c2d-022e-4041-84bc-e219a1739a0f.png)

**Comment by Ghostbird** [comment]
This is in my _Sound_ menu:
![Screenshot_20220102-153734](https://user-images.githubusercontent.com/1202149/147879342-b5481c0c-7817-4992-bc38-64260a7e1d0b.png)
Even though it is off, ASK will vibrate when I type, unless I override it in ASK itself.

**Comment by Ghostbird** [comment]
The issue is still present in the beta version

**Comment by menny** [comment]
Was that working for you before the update?

**Comment by Ghostbird** [comment]
Yes, as I wrote in my initial post. ASK has always correctly used the system setting (including that switch) in the past. Only with the update I received December the 3rd, it would no longer conform to that setting. I compared it to the Google keyboard which still correctly uses that switch's setting.

**Comment by menny** [comment]
here is the fix: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3131

**Comment by menny** [comment]
I will promote this to beta later tonight. If you are registered to the beta channel you should get it by tomorrow.

**Comment by SergeantSphincter** [comment]
Good evening, for some reason my keyboard keeps switching to smaller keys randomly.  When I hit the keyboard button at the bottom left and switch to a different keyboard, then switch back, the problem corrects itself for a time.   But I hate the squished keys, not sure why it's happening?
 I have a Samsung S23 Ultra, thank you for any help you can provide   😃



Sent from Yahoo Mail on Android 
 
  On Sat, Dec 4, 2021 at 10:07 AM, ***@***.******@***.***> wrote:   I feel like a huge ass, how did I miss that?   I'm so sorry!   Thank you for your help.  I've had ASK for 10 plus years, I recommend it to everyone.   Yall have an amazing product.  
Thanks again!     Mary

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 4, 2021 at 9:36 AM, Gijsbert ter ***@***.***> wrote:   

   
   - In the ASK app, click the middle icon in the bottom bar (the palette icon). You'll end up in the UI menu.
   - Click the option Keyboard effects and experience
   - Disable the checkbox Use system vibration (this one is misbehaving)
   - Set the Vibrate on key-press time to 0 milliseconds

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
