### ISSUE TITLE
HUGE FAN - I have been using for Android , somehow got iphone and missing double tap for Latvian ē, ā, ž ļ .etc PLEASE consider IOS version

### ISSUE THREAD

**Issue by aintnogeek** [AnySoftKeyboard/AnySoftKeyboard#3359]
### Steps to reproduce
1.
2.
3.

### Actual behaviour

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by alchemiker** [comment]
To publish an app to the Apple App-Store requires the developer to pay an annual fee of 99$ beside all the nuisance of translating the code to another programming language and making it functional for another operation system, running through the whole process of verification and distribution through the App-Store... 
If that's something you desire you are free to do so yourself, the code is open-source.

**Comment by drelephant** [comment]
Sometimes the walls are high enough to obscure the fact the garden isn't actually green.

**Comment by aintnogeek** [comment]
> To publish an app to the Apple App-Store requires the developer to pay an annual fee of 99$ beside all the nuisance of translating the code to another programming language and making it functional for another operation system, running through the whole process of verification and distribution through the App-Store...
> If that's something you desire you are free to do so yourself, the code is open-source.

First  year being in appstore on me if you decide. I think you have good base of userswho really love your app. I would pay for such app. Can you make pull of smthng and you will know.

**Comment by alchemiker** [comment]
@aintnogeek I'm not a developer for this keyboard, I only answer questions and write a little bit documentation when I have time. I just think you underestimate the effort that is needed to a) create, b) release, and c) maintain(!) such an app. Look here on github, we currently have 679 open issues only for the Android version of this app. Even if the developer (who creates this app alone, in his free time, without getting paid, as I understand) would find the time and energy to rewrite it for iOS (only the main app, the language packages are a separate problem), it would be twice as much effort to sustain ASK, because there would be not only bugs in the android version, but in the iOS version, too, and every new feature developed would have to be implemented in both apps. 

I didn't mean to say that your idea is bad or impossible, I just wanted to point out that such requests are maybe a little bit too much asked for an open-source developer. Like you can't bother to get a device where this app would work on and they have to put weeks of unpaid work into creating an app version just because of that.
