### ISSUE TITLE
Backup settings fails

### ISSUE THREAD

**Issue by IOI-655321** [AnySoftKeyboard/AnySoftKeyboard#3551]
### Steps to reproduce
1. Open AnySoftKeyboard app
2. Go to backup settings
3. Choose custom path, show failed

### Expected behaviour
It should backup settings to an XML file

### Actual behaviour
Error 'failed to access storage folder' leaves 0 file size XML file.

I tried uninstalling and reinstalling in case a permission wasnt set properly but this didnt help. 

**Android OS version:**
Android 13 (one ui 5)

**Device manufacturer and model:**
Samsung s21 ultra (exynos)

**List of installed add-ons (like languages, or themes):**
None

**Comment by ipkpjersi** [comment]
I'm also experiencing this on Android 11 (OxygenOS 11) on my OnePlus 7 Pro. The app AnySoftKeyboard even has storage permissions yet it fails to write the backup xml file.

**Comment by menny** [comment]
I think that this is solved with the latest beta build. Have you tried?

**Comment by ipkpjersi** [comment]
I joined the beta program on the Play store but it said no updates were available, the latest build was from November 2021. I also tried building this app directly from main, but it fails to install the APK (I think because I have the stable version already installed).

I can uninstall my current version and install the latest main built APK directly, but then I'd lose any of my custom settings which kind of makes this issue itself a bit of a catch 22.

I'll probably go ahead and try installing the latest main built APK directly anyway just to confirm if this issue is solved.

**Comment by menny** [comment]
Which version do you see when using the beta channel?

**Comment by ipkpjersi** [comment]
I do see a beta build from November 2022 now, and I was able to install it and then successfully restore my settings from Gdrive. Hopefully there will be a new stable release with these fixes since it's working well now.

**Comment by menny** [comment]
Great! Thanks for verifying
