### ISSUE TITLE
[Feature request] Add "Clear history" button to clipboard history

### ISSUE THREAD

**Issue by tsilvs** [AnySoftKeyboard/AnySoftKeyboard#3612]
# Expected behavior

A small button with a thash bin icon on top of the clipboard history window would suffice.

**Comment by DaRealNOX** [comment]
I have been laboriously deleting the ASK Clipboard by hand every day for over half a year of use.

Of course, this is extremely annoying because, on the one hand, the clipboard is buggy (entries are ALWAYS recorded twice, but have to be deleted individually!) and, on the other hand, the list eventually becomes endless because it does not synchronize with the Android clipboard.

So perhaps as a solution you could either offer synchronization with the Android Clipboard (the simpler, but not as data-safe method) or you could actually build in a deletion function like @tsilvs describes, using the trash icon.

But one thing is certain:
Such a feature is needed because it is incredibly tiring to regularly delete everything by hand. So pleeeeeeease (with lots of whipped cream on top) dear developers, take care of it soon. You will see that the number of users will also increase. Many people are so put off by this fact that they don't even want to try ASK.

**Comment by tsilvs** [comment]
[This Java class](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/7bb330cbf08b9503f8dec1ba4cd7d7599c878faa/ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboard.java#L290) method (`showAllClipboardEntries`) is responsible for opening a clipboard options dialog with data (calling `showOptionsDialogWithData`).

**Comment by DaRealNOX** [comment]
@tsilvs 
Thanks for pinging.

**Comment by menny** [comment]
Fixed in the latest beta

**Comment by DaRealNOX** [comment]
@menny Hmmm, no changes in v1.11-r1 found (which I have installed atm). Which version is the "beta"? When I search through the releases here on github, I only find a "Beta 2" from November 5th, 2015. Confusing.

**Comment by menny** [comment]
You can sign up as a tester in Play Store. Or download an unsigned APK from GitHub (in which case, you lose your ability to update from the Play Store or any other store). What do you prefer?

**Comment by DaRealNOX** [comment]
@menny I prefer the download of the unsigned APK to test it in my sandbox first. After all things are checked I will install it to my mobile devices and give feedback here, ok for you?

**Comment by DaRealNOX** [comment]
Sorry for replying that late...

Tested with MEmu (9.1.1.0x64) and Android Studio (Windows-2023.2.1.23x64), the function described works flawlessly! :)

I just don't have it installed on my phone yet because I want to wait until the official version, because I noticed in my currently installed version that it doesn't let me export the config. But I have already installed it on my tablet and the clipboard function works flawlessly there too. Thanks @menny!
