### ISSUE TITLE
is this project dead? no updates in f-droid.

### ISSUE THREAD

**Issue by jwalantsoneji** [AnySoftKeyboard/AnySoftKeyboard#475]
There seems to be no releases for ASK in f-droid since 2013.
Is the project dead or not getting updated in f-droid?

**Comment by menny** [comment]
ASK is alive! Unfortunately, f-droid stopped updating it. At first it was because of a binary issue, but that was solved, so.. I have no idea.

In any case, you can either download the latest release from Google Play Store, or from github at: https://github.com/AnySoftKeyboard/AnySoftKeyboard/releases

**Comment by jwalantsoneji** [comment]
Is there something I can help with in putting it on f-droid?

**Comment by menny** [comment]
There is a ticket for _f-droid_ : https://gitlab.com/fdroid/fdroiddata/issues/20
you can check there
