### ISSUE TITLE
Missing symbols key on bottom bar (Alternate layout)

### ISSUE THREAD

**Issue by xavihernandez** [AnySoftKeyboard/AnySoftKeyboard#544]
Hi, there are several bootom bar which we can choose, but most of them have little space bar.
The only one which has a larger space bar... misses symbols key. Indeed on the left side there is a "switch language" key, which is redundant with the space bar behavior to switch between languages. I think we should remove this "switch language" key on the left and replace it by a symbols key.

**Comment by xavihernandez** [comment]
I have found a way to get symbols, using gesture. But a key seems to be missing.

**Comment by menny** [comment]
Are you suggesting a new bottom row?

**Comment by xavihernandez** [comment]
Hi @menny,

AFAC, I think a key "Symbols" should be in bottom row. Because we have to use gesture in order to get symbols keyboard in Alternate layout bottom row. Maybe instead of the "World" (language switch) key. I love "Alternate layout" bottom row because of its large Space key. But I have to use gesture to get symbols keyboard, which is kinda weird.

**Comment by moshpirit** [comment]
Why not an interactive UI layout where the user could modify the buttons without default configurations? I'm also missing this option because I'm not used to slide the keyboard yet but I love the KISS philosophy and I would change the microphone and keyboard icons to a symbol button. Also would give us a brilliant customization of the symbol keyboard.

I'm not a developer,  just a new user of this incredibly cool keyboard so I don't know how difficult can be developing it.

Thanks a lot!
