### ISSUE TITLE
Possible license violation

### ISSUE THREAD

**Issue by adolfintel** [AnySoftKeyboard/AnySoftKeyboard#560]
Take a look. Definitely looks like your keyboard
https://play.google.com/store/apps/details?id=com.menny.android.effectedkeyboard

**Comment by menny** [comment]
yes, this is a license violation.
Thanks for pointing me to it.

**Comment by sabergeek** [comment]
@menny Umm isn't your app licensed under Apache 2.0? I'm not sure how this is a violation since the license allows re-distribution of code for commercial purposes.

**Comment by menny** [comment]
It is (was?) a license violation since they did not an attribution set up

**Comment by VitaliPom** [comment]
Test

**Comment by VitaliPom** [comment]
Hi, I remember I read every line in your Apache License and exactly mentioned your keyboard, I very very very apologies if it disappeared if it has it was by mistake, but I did have mentioned anysoftkeyboard I even sent you a mail and you replied I think from new York at the time. Ehm I'll check it in ASAP

**Comment by VitaliPom** [comment]
Yes, looks like I accidentally erased it from the new GUI I made, Uhm.. I'm sorry? :)
How much time do I have to fix it?

**Comment by menny** [comment]
No worries. Take your time, but please fix it.

**Comment by VitaliPom** [comment]
Tried to recompile yesterday, I'm having recompiling issue since my source code was erased accidental y along with the git repository and I couldn't use `apktool` since I could not recompile backwards after decompiling, alas meanwhile I'm rewriting the whole source back so I apologies for the long delays, as I  mentioned the new version without the license is fairly new and the old one had the license mentioning explicitly.

**Comment by menny** [comment]
Wow.. that's shitty.
Can you add explicit attribution in the Play Store and any other place you distribute the apk? 
This should be enough, no need to recreate the source if it's too much trouble

**Comment by VitaliPom** [comment]
Sure
I will add in playstore I'm recreating the code anyways uhm or wait uhm in
playstore I think I'm not allowed to add 3rd party application referals,
I'll check these.

**Comment by VitaliPom** [comment]
Anything I add there hides the sells message with the overflow which is
auto added once I have more than two lines, I'm not disterbuting or
commercializing this version anymore once I found out I had to recreate the
code and I'm pretty sure at 99.99% that the old version with the gray logo
is referring to Anysoftkeyboard explicitly from inside and it appears like
1000 times everywhere compared to this disterbution version. Please let me
recreate the code base, I began doing so today guess in 2-4 months I'm done
with that version and I'm able to create a normal standalone referal this
time, in the previous version it was crappy since it appeared only in a
license which was awefully prettified so let's don't harsh to kill me for
that :D I will do my best for Anysoftkeyboard and for my keyboard, which
goes hand in hand with yours.
thanks,
Vitali

P.S Glad to meet you now finally, four years afterwards!!!!!!

**Comment by menny** [comment]
As you wish. Good luck.

**Comment by VitaliPom** [comment]
Found a place to make it meanwhile, I put a reference without the copied Apache2 License yet in the link of Privacy Terms inside the google app reference, this is the only place that contains rough text now.

**Comment by menny** [comment]
Thanks
