### ISSUE TITLE
Creating a new language pack from a txt file

### ISSUE THREAD

**Issue by ghost** [AnySoftKeyboard/AnySoftKeyboard#567]
Hi,

I have a text file of words using which I want to create a language pack (dictionary) and then bundle it with anysoftkeyboard. How do I do this? 

I've converted it into an xml file and the next step should be to convert it into a binary dictionary as shown here (https://code.google.com/archive/p/softkeyboard/wikis/BinaryDictionaries.wiki), but this repository doesn't contain the makedict program. 

Can someone please help me out?

**Comment by homersimpsons** [comment]
I think you need to use file in AnySoftKeyboardTools: https://github.com/AnySoftKeyboard/AnySoftKeyboardTools

**Comment by adeshp96** [comment]
@SpandanMadan Were you able to integrate the .dict file with the keyboard?
I am trying to integrate the dict file generated with Indic Keyboard(derived from Android's Latin IME) but failed. I was able to produce the .dict file successfully with AnySoftKeyboardTools but replacing the .dict file with the main_en.dict(the default english dict file in Indic keyboard) doesn't work (i.e. the predictions don't show up in the app - app works fine otherwise). Does the dict produced by AnySoftKeyboardTools different from the one Latin IME uses?

**Comment by menny** [comment]
There are several types of inputs that can be used to generate a valid dictionary APK.

1. an AOSP file - should be located under `pack/dictionary` folder, and include a file named `aosp.combined.gz`
1. pre-built xml files - should be located under `pack/dictionary/prebuilt`
1. plain text files - should be located under `pack/dictionary/inputs`

See the English pack at https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/master/addons/languages/english/pack/dictionary
