### ISSUE TITLE
poor prediction / suggested words

### ISSUE THREAD

**Issue by grrrrr** [AnySoftKeyboard/AnySoftKeyboard#694]
### Steps to reproduce
1. start typing words
2. get poor predictions
3. (see "Actual behaviour" below
### Expected behaviour

More accurate predictions.

e.g. 
- If you start typing the word, offer up  the singular version first instead of the plural/past/future and having the singular 4 or 5 suggestions down if at all
### Actual behaviour

Predictions for words appears to be quite poor

| Typing | Gives | Expected |
| --- | --- | --- |
| fal | false / falls / falling / fall | Why not suggest _fall_ earlier |
| wal | Wales / Waller / walks / Walter / Waller's / walk | Why not _walk_ earlier, what on earth is _waller_ |
| lov | / log / loved / loves / loving / love | again _love_ seems more logical to suggest earlier |
| th | that/ than / they / them / then / this / though / through / the | _the_ is way down the list, would expect to at least come before though and through |
| wiat | wish/wistfulness/ Wisteria / .... | expected to correct to _wait_ but not suggested |
| milliona | millions / million's / millionairess / millionaire | would expect _millionaire_ first |
| lin | lines / line / link /... | expect _line_ to be first option |
| yo | to / go / your / you / you're | expect you to be an earlier suggestion |

More as I recall them

**Android OS version:**
Android 4.4.4

**Device manufacturer and model:**
Samsung Galaxy S4

**List of installed add-ons (like languages, or themes):**
No add-ons, just AnySoftKeyboard with "English QWERTY keyboard" 

Next words suggestions set to "suggest next words"
Next word aggressiveness set to "Medium"
Quick fixes and abbreviations set to "on"
Learn method set to "after some usage"
contacts dictionary is "off"

**Comment by alekksander** [comment]
This is exactly why i have to use big corporations software — poor prediction here on AnySoftKeyboard. Using virtual qwerty keyboard can be really hard to do with just two fingers, as qwerty is designed to be operated with ten. As so, virtual keyboards got to have good prediction algorithms to make using it less painful experience. This is really vital in my opinion. I don't have time to click every single button correctly on my tiny 5 inch screen. Some other popular applications can often predict a word even if i type complete nonsense, yet this nonsense turns out to be correct word if every tap was few millimeters to the right of left, and it can „decode” it.
This application already is very configurable, **fast**, nicely designed and most importantly — open sourced… but lack of the core — which is good prediction service makes it hardly usable… hopefully more users agree on that and devs can find some extra time to retrieve what's missing.

**Comment by menny** [comment]
I've updated the dictionary with many more words and more precise frequencies. Please try the latest beta.

**Comment by alekksander** [comment]
english only?

**Comment by menny** [comment]
only the English dictionary is included in the AnySoftKeyboard main app. Other languages should update their dictionary

**Comment by alekksander** [comment]
Did You create dict. from wikipedia?

**Comment by menny** [comment]
no, from AOSP. So the English dictionary should be on par with AOSP keyboard.

**Comment by grrrrr** [comment]
@menny is this in 1-8 R8?

**Comment by menny** [comment]
Yes. It is in the latest release.

**Comment by alekksander** [comment]
where do i find info how to build my own dict? i think i saw it somewhere, but can't remember where…
