### ISSUE TITLE
Migrate alternative layouts to main APK

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#902]
colemak
dvorak (also include ń)
qwerty_compact
terminal

**Comment by menny** [comment]
@friesenkiwi interested in doing this?

**Comment by friesenkiwi** [comment]
@menny Yes, actually this is a dupe of https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/748, also https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/422 and https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/579 are related.

I did want to take a stab at those, as soon as the LanguagePacks are all finished ;-)
Need to try to compile AnySoftKeyboard first, never did anything with the NDK.

**Comment by menny** [comment]
@friesenkiwi let me know how I can help, but I'm going to guess that if you have NDK installed, you wouldn't have any problems compiling ASK

**Comment by friesenkiwi** [comment]
Ok, good to know! :-)

**Comment by asterismo** [comment]
👍

**Comment by friesenkiwi** [comment]
OK, after installing the NDK, the build went smooth, so I should actually be able to work on this issue.

**Comment by menny** [comment]
Nice!

**Comment by asterismo** [comment]
Dvorak spanish variant also swaps the R with the H, can't wait to have it! Please, upload it to FDroid asap!

**Comment by friesenkiwi** [comment]
@asterismo What do you mean "swaps the R with the H"? Is there something to be changed in the Spanish pack or  to be considered when migrating AlternativeEnglishLayouts?

**Comment by menny** [comment]
Thank you @friesenkiwi.

**Comment by menny** [comment]
A beta release will be available later today for testing

**Comment by menny** [comment]
Actually, it will be available as alpha in a few minutes

**Comment by asterismo** [comment]
Spanish Dvorak variant changes places of H and R besides adding the Ñ. It is default now in most linux distros, https://es.m.wikipedia.org/wiki/Teclado_Dvorak It really should be considered because there will be a difference between the PC and phone... I have installed an extra APK from GPlay named Alternative Layouts which is not available in FDroid... this should be bundled with the base app.

**Comment by friesenkiwi** [comment]
@asterismo the Dvorak and other keyboards from the AlternativeLayouts app are now merged into the main app (that's the purpose of this issue), and will be available in the next release.
However, the main app is somewhat the "English" Language Pack. If there is a special Spanish Dvorak variant, it should most probably be included into the Spanish pack?
I tried to start one like that (https://github.com/friesenkiwi/LanguagePack/commit/f4001de1c08dd36f43a3adec2e1cad9e71f38f9c). There are still some special keys and symbols to be adapted, so feel free ;-)

**Comment by asterismo** [comment]
Ok that makes perfect sense. I downloaded the spanish language pack but i think is only a dictionary, not new keyboard layouts.

**Comment by friesenkiwi** [comment]
The changes I made are not released through Play Store or official F-Droid repository.
You could build the pack yourself, or you can get a kind of "beta" version in my private F-Droid repo at https://fdroid.denk-nach-mcfly.de/fdroid/ or download the APK directly at https://fdroid.denk-nach-mcfly.de/fdroid/repo/LanguagePack-es-release.apk. You would need to remove the official Spanish pack before installing this development version.

**Comment by asterismo** [comment]
ok! thanks! let me know when you add to it the spanish dvorak variant. cheers and keep up the great work!

**Comment by friesenkiwi** [comment]
The Spanish Dvorak variant IS included in that development version at https://fdroid.denk-nach-mcfly.de/fdroid/repo/LanguagePack-es-release.apk and it would be very helpful, if you could test it :-)

**Comment by asterismo** [comment]
woha! it is awesome man! i can think on a few tweaks on overall dvorak key positions... are you open to suggestions?

**Comment by friesenkiwi** [comment]
Sure I am :-) Fire away.

**Comment by asterismo** [comment]
See https://jabber.undernet.uy:5281/upload/7a65894d-d6a0-4c02-9735-e6709bd3c282/1yy6It4tTpiy0j6OCY-Q7g.jpg That is a correct spanish dvorak layout. You could try tho following
1) remove the [ ' ] character from upper left
2) Place the [ ñ ] as the first letter in the upper row
3) flip the [ . ] with the [ , ] as in spanish variant
4) option a) remove the [ . ] and [ , ] from the bottom row and enlarge the spacebar, which could be great
4) option b) keep the [ . ] and [ , ] un the bottom row, and remove them in the upper row, and use the free space to place [ shift ] and [ backspace ] which would give more space in the bottom row.
The R and H flip has already changed my life man

**Comment by friesenkiwi** [comment]
Could you do a screenshot of the current for me? :)

**Comment by asterismo** [comment]
here https://jabber.undernet.uy:5281/upload/02dce315-1e3d-4a57-a61c-b5ff7f7ec36e/YKulOdRvSb-a9-rZ_N0Jzg.jpg

**Comment by friesenkiwi** [comment]
OK, I made some changes to the first row according to your suggestions (',.p -> .,ñp). Does this help you?
The bottom row is independent from the chosen keyboard layout (you can change it in the app's settings), so I can't alter it.
Albeit it is somewhat redundant, I chose to let . and , stay there, because I have no idea how to put a function key there and removing them and making the other keys bigger would make the layout somewhat unbalanced (and deviate it from the original dvorak), I guess. But since I'm not using the layout anyway and right now you seem to be the only stakeholder, you can suggest the way you like and I will try to implement it :-)
The new .apk is at the same location as the last one, I didn't change the version number, so you probably need to uninstall the old one before installing the new.

**Comment by asterismo** [comment]
Thanks man, it looks sweet! https://jabber.undernet.uy:5281/upload/c94c4cbc-eb9a-41bc-b383-947b6c9ac955/rmg69LhSTfqJFYHhE3Xf3A.jpg I'll think some alternative and let you know. Cheers!

**Comment by friesenkiwi** [comment]
OK, sorry, I had another look at the layout and realized I must have been confused before. :dizzy_face:  Since backspace and shift were already there, it wasn't very hard to move them to the top row.  But since in the first row there are only 8 keys left, I also had to remove the numbers on long-press.
I used the the space in the second-to-bottom by ç.
Check it out :)

**Comment by asterismo** [comment]
It is very nice, but i have some suggestions.
1) The backspace key lies near the send key, fact that could cause problems but it is too early to state that, so my take on that is +1 for the new placing of [ shift ] and [ backspace ] keys
2) The [ ç ] breaks the layout a bit since its located on the home row, not bottom one, and plus, it breaks the layout in the sense that for example, the [ q ] key, lies between the [ o ] and [ e ], but in the new layout it lies under the [ a ], too far to the left. My take on that would be to make a "Catalan" variant with the [ ç ] and leave the spanish variant without it and with a better centering of the keys in the bottom row, (or maybe migrate that variant to the Catalan language pack...)
As a final comment, if you apply this changes, this layout would be the best spanish Dvorak i've ever seen. Best regards

**Comment by friesenkiwi** [comment]
Can you send another screenshot? :-)

**Comment by asterismo** [comment]
yeah, sorry i forgot, https://jabber.undernet.uy:5281/upload/d41051d7-b4b1-4dd0-a883-40eeb6459aee/UJX6MzDOScC8q3T9JIzw6g.jpg

**Comment by asterismo** [comment]
hete is a physical keyboard https://jabber.undernet.uy:5281/upload/a56e74a7-0ed6-4212-9e03-fbd11c234e58/isU9GDqZROGeWLxTByys3Q.jpg
See the location of the [ q ] in relation to the [ a ] in addition, the [ ç ] character is more like a symbol character, so one more reason to remove it from the row and re-center the entire bottom row

**Comment by friesenkiwi** [comment]
Well yeah, obviously, the ASK display layout is a deviation from the physical layout. To some extend it maybe has to, just because it makes no sense to have all the keys at the same time and the multiple layers.
Also, probably many of the thoughts which led to the design of dvorak as a physical key 10 finger layout in the first place can't really be applied one-to-one on a touch keyboard which is largely operated by two thumbs ;-)
So, do you think it's OK if you test the layout for a couple of days in daily usage and later report back, whether we should check it in like this or alter it?

**Comment by asterismo** [comment]
Yes, i'm already testing it. The [ ç ] character is really a symbol character and it is not used in spanish at all, it really should be removed. That way i think it would be the closest to dvorak as possible in a spanish variant.

**Comment by friesenkiwi** [comment]
OK, I removed that key again. You can download the new version at the same URL again if you like.

**Comment by asterismo** [comment]
Ok, what i ment is to the bottom row to be re-centered and keys the same size, like this qwerty's middle row. https://jabber.undernet.uy:5281/upload/b4adbb4f-5fd3-42c8-9ed7-6218400af072/xX9-6slNSUi_Lk0T7NIGQQ.jpg Can you do that final tweak? this is the current layout. https://jabber.undernet.uy:5281/upload/defbfc21-72a3-40c5-9ee0-f162ef7a0343/yidjozqpRguTn65A-rKROQ.jpg

**Comment by friesenkiwi** [comment]
Huh, OK... to me that looks like waste of space, but you're the doc, doc ;-)
Changed accordingly and updated apk.

**Comment by asterismo** [comment]
Lol! You have done a great job! this is exactly how i pictured it! You are a great developer, thanks! https://jabber.undernet.uy:5281/upload/f02f4263-be97-4382-813a-9d34cfb5573b/TwQZaxLLRQif4XGfqxs1qw.jpg

**Comment by friesenkiwi** [comment]
Well, thank you for that... I didn't do much, though. It was just some little changes in the XML.
So, report back after a test phase, so I can put up a Pull Request.

**Comment by asterismo** [comment]
Well, i have tested the layout and i must say it is great. The only issue is that the [ e ] and [ u ] keys do not have the tildes and special characters Add that up and submit a PR. I'm a very happy dvorak user. 😃

**Comment by friesenkiwi** [comment]
Thanks for your testing and feedback! I added those popup characters and put up a PR: https://github.com/AnySoftKeyboard/LanguagePack/pull/60 . The new version is also available as a preview APK as before.

**Comment by asterismo** [comment]
i'm already installing it. Thanks!
