### ISSUE TITLE
Return Key is Drawn off the Screen

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#971]
The green return key is drawn on my screen with a right margin too far to the right, a little off the screen. It doesn't line up with the keys above it.

I have a Nexus 5X with Android 6.0.1 and I am using "English QWERTY Latin keyboard with symbols (on long press)" and the "New Generation - Testing" layout.

Does anyone else see this?

**Comment by menny** [comment]
Can you provide a screenshot?

**Comment by landry314** [comment]
Well, this is the screenshot. I cropped it to eliminate personal information.

![Uploading screenshot with return key to right.png…]()

**Comment by landry314** [comment]
something is wrong with github right now. It won't upload my screenshot (i tried two different formats) and it just glitched out and said i closed this issue. how would i close this issue if i am not the owner?

i will try to upload the screenshot again tomorrow. please open the issue again. how strange.

**Comment by landry314** [comment]
![Uploading screenshot with return key to right.png…]()

**Comment by landry314** [comment]
![screenshot with return key to right](https://cloud.githubusercontent.com/assets/6866501/25365923/56935cc4-2929-11e7-8865-54d81bd5eb7f.png)

**Comment by menny** [comment]
got it.
thanks.

**Comment by landry314** [comment]
I have a Pixel 2 now with Lineage OS 16 and still, my return key is drawn off the screen...

Obviously my theme is "Simple black glow" with a "Simple" bottom row and "English QWERTY Latin keyboard with symbols (on long press)".

![keyboard drawn return key](https://user-images.githubusercontent.com/6866501/55257131-55ef4800-5235-11e9-8a35-7b257ce25f9e.png)

**Comment by ArenaL5** [comment]
Already fixed... at some point in time. Please close.

@AnySoftKeyboard: Please don't mind me asking to close several issues. I've noticed your repos are marred with invalid or duplicate issues, and minor bugs, and I'm trying to help to take some weight off the backlog.

I hope this helps.

**Comment by landry314** [comment]
Well, if this is fixed it hasnt been incorporated into a released version yet because I have the newest version and it is still broken. So, I am waiting to actually see it fixed before I close the issue.

**Comment by ArenaL5** [comment]
That's fair, and I apologize. I've just realized now the error isn't fixed, I've made a mistake while debugging.

You probably already know all of this, but I'll leave this information here just in case someone, or myself, tries to fix it:

---

This error only happens if the "change keyboard" is hidden because you've only enabled a single layout. The gap where that key would be (between 123!#() and comma) has twice the width it should have, and pushes the Enter key off-screen. This never happens if there are more than one 
layouts selected.

It happens with every theme, but it's easier to see with the theme you're using, "Simple black glow".

It affects every bottom row with has this code (which is every one of them except Regular):

```
        <Key ask:isFunctional="true" android:codes="@integer/key_code_mode_alphabet" ask:showInLayout="if_applicable"
             ask:longPressCode="@integer/key_code_cancel" android:keyIcon="@drawable/sym_keyboard_cancel"
             ask:hintLabel=" " android:keyEdgeFlags="left"/>
```
