### ISSUE TITLE
[Feature Request] Fleksy-like gestures

### ISSUE THREAD

**Issue by LoveIsGrief** [AnySoftKeyboard/AnySoftKeyboard#996]
First of all thanks for the great, opensource keyboard!

I'm currently using [Fleksy](https://fleksy.com/) and it using swipe gesture editing, which would be great to have in this keyboard too. [video demo](https://youtu.be/GqjJ-JNcFGk?t=41s)

Basically the missing gestures actions are:

- [ ] Delete last word
- [ ] Last suggestion or add to dictionary
- [ ] Next suggestion
- [ ] Add space after word | Add dot after space

And that's it!

Cheers :)

**Comment by maverick74** [comment]
I'm not sure i'm understanding you right... if i am, then almost everything is already available:

**Delete last word** (swipe delete key to the left)

**Last suggestion or add to dictionary** (if you type manually it should ask you to add/remove the word - just press on it! If not go to: Menu > Special dictionaries > Automatic Dictionary > Select the learning mode

**Next suggestion** (isn't this standard?! It should be showing you next suggestions by default, if not go to: Menu > Special dictionaries and enable it)

**Add space after word** (it does after a suggestion. go to Menu > Language > Even More > Tweaks > Space after suggestion)

**Add dot after space** (It's not the same but may work for you. Go to: Menu > Language > Even More > Double space for dot)

**Comment by menny** [comment]
@LoveIsGrief can you provide more info? Wrt @maverick74 reply.

**Comment by LoveIsGrief** [comment]
@maverick74 & @menny  , I suggest you watch the [video](https://youtu.be/GqjJ-JNcFGk?t=41s) to see the difference or use the app for a day.

I'm not sure why, but putting those actions as gestures just makes typing much faster for me, in fact they have a [guinness world record for the fastest text message](http://www.guinnessworldrecords.com/news/2014/5/fastest-touch-screen-text-message-record-officially-broken-with-fleksy-keyboard-57380/) and more [awards](https://en.wikipedia.org/wiki/Fleksy#Awards). They must be doing something right with their mode of editing.

**Comment by maverick74** [comment]
@LoveIsGrief I already knew Fleksy (like Minuum, TouchPal, Hackers Keyboard and a few others). They all have good things and as such it depends a lot on the users tastes…
I, personally, don't like to be bombed with publicity, hate to be traced or not knowing if my keyboard is spying on me, and - very unfortunantely - i'm not rich to be spending money on keyboards… Also, i love FOSS ideals, lite apps and love to be able to configure everything to my taste.
That leaves me with ASK. (Even if Hackers Keyboard is also a good option for ssh, but much much less configurable).
Almost any keyboard have strengths others don't.

Menny is a great guy, and if he sees this might be a good idea he'll for sure find a way sooner or later

**Comment by LoveIsGrief** [comment]
@maverick74 my move to ASK is also due to my wish for privacy. If I can migrate with some of the functionalities I'm used to, it'll be great :)

I would implement this myself, since it doesn't seem like much, but setting up a development enviroment for android seems like such a hassle...

**Comment by j-mikhail** [comment]
I'd like to echo this request, especially since it seems to have stalled. Now that Fleksy is selling out big time, I would love to switch to ASK, but I've come to depend on some of Fleksy's gestures.

Here's an another example not previously mentioned: most keyboards will insert a period if you double-tap on space, but Fleksy allows you to subsequently change that period to other punctuation marks by swiping up and down afterwards. I would love to see that kind of functionality implemented in ASK. Doable?

**Comment by j-mikhail** [comment]
Replying to unstale. Almost 2 years later, would still love to see this functionality added!

**Comment by LoveIsGrief** [comment]
Oh wow, time has indeed passed. Though it's now possible to delete the last word, but it doesn't delete the previous space so 2 swipes are necessary.

**Comment by maximbaz** [comment]
> Though it's now possible to delete the last word, but it doesn't delete the previous space so 2 swipes are necessary.

This has been now fixed in https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2490, but the other gestures are missing, I personally particularly miss the gesture for next/previous suggestion.

**Comment by PremPatel8** [comment]
One of the best features of Fleksy for me was the ability to add a space by swiping right anywhere on the keyboard, because this allows you to type a lot faster without having to waste time tapping the spacebar at the bottom of the keyboard after every word. I have already configured the swipe left gesture to delete words, now if this basic "add space" action was added as a option then it would make the swipe right gesture a lot more useful. If someone could give me any pointers about the codebase and functionality I will try to implement this feature myself.
